name: Manual Workflow Test with inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
      age:
        description: 'Age'
        type: number
        required: true
        

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello ${{ inputs.name }}"

      - name: Age
        run: echo "Hello ${{ inputs.age }}"
