name: Manual Workflow Test with inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
      age:
        description: 'Age'
        type: number
        required: true
      gender:
        description: 'Gender'
        type: choice
        options:
          - Male
          - Female
      married:
        description: 'Is Married'
        type: boolean
        
      
jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello ${{ inputs.name }}"

      - name: Age
        run: echo "Age is ${{ inputs.age }}"

      - name: Gender
        run: echo "Age is ${{ inputs.gender }}"

      - name: Married
        run: echo "Age is ${{ inputs.married }}"
